### PR TITLE
KarelJanVanHaute/issue134

### PR DESCRIPTION
**Pull request by KarelJanVanHaute**

### CODE REVIEW

**Comment by KarelJanVanHaute** [comment]
There are two test added to the frontend stack. 
A A11y tester that uses pa11y-ci under the hood.
And a html tester that I wrote myself, inspired by the pa11y code, that uses html-validate under the hood. 
You can call them by using these commands:
```
$ yarn test-a11y
$ yarn test-html
```
They both use the BASE_URL variable from the .env file to get the craft sitemap. This sitemap gets parsed to get a list of all url's in the site. And the tests are then performed on these URL's.

**Comment by janhenckens** [comment]
Can you also add this to the readme @KarelJanVanHaute?

**Review by janhenckens — APPROVED** [review]

**Review by janhenckens — APPROVED** [review]

**Review by janhenckens — APPROVED** [review]

**Review by janhenckens — APPROVED** [review]

**Review by janhenckens — APPROVED** [review]

**Review by Numkil — APPROVED** [review]
Ziet er goed uit vind ik 👍

**Comment by janhenckens** [comment]
Merged, let's go 🚀

**Pull request merged**
